# Resources/config/routing.yml
edm_directory_delete:
    path:     /edm/directory/delete/{id}
    defaults: { _controller: "EDMBundle:Document:delete" }
    methods:  [GET]

edm_directory_edit:
    path:     /edm/directory/edit/{id}
    defaults: { _controller: "EDMBundle:Document:edit" }
    methods:  [GET, POST]

edm_directory_index:
    path:     /edm/directory/index/{id}
    defaults: { _controller: "EDMBundle:Document:index", id: null }
    methods:  GET

edm_directory_move:
    path:     /edm/directory/move/{id}
    defaults: { _controller: "EDMBundle:Document:move" }
    methods:  [GET, POST]

edm_directory_new:
    path:     /edm/directory/new/{id}
    defaults: { _controller: "EDMBundle:Document:new", id: null }
    methods:  [GET, POST]

edm_document_delete:
    path:     /edm/document/delete/{id}
    defaults: { _controller: "EDMBundle:Document:delete" }
    methods:  [GET, POST]

edm_document_edit:
    path:     /edm/document/edit/{id}
    defaults: { _controller: "EDMBundle:Document:edit" }
    methods:  [GET, POST]

edm_document_move:
    path:     /edm/document/{id}/move
    defaults: { _controller: "EDMBundle:Document:move" }
    methods:  [GET, POST]

edm_document_upload:
    path:     /edm/directory/upload/{id}
    defaults: { _controller: "EDMBundle:Document:upload", id: null }
    methods:  [GET, POST]
