# Resources/config/routing.yml
edm_directory_delete:
    path:     /edm/directory/delete/{id}
    defaults: { _controller: "EDMBundle:Directory:delete" }
    methods:  [GET]

edm_directory_edit:
    path:     /edm/directory/edit/{id}
    defaults: { _controller: "EDMBundle:Directory:edit" }
    methods:  [GET, POST]

edm_directory_index:
    path:     /edm/directory/index/{id}
    defaults: { _controller: "EDMBundle:Directory:index", id: null }
    methods:  GET

edm_directory_new:
    path:     /edm/directory/new/{id}
    defaults: { _controller: "EDMBundle:Directory:new", id: null }
    methods:  [GET, POST]

edm_document_delete:
    path:     /edm/document/delete/{id}
    defaults: { _controller: "EDMBundle:Document:delete" }
    methods:  [GET, POST]

edm_document_upload:
    path:     /edm/directory/{id}/upload
    defaults: { _controller: "EDMBundle:Document:upload", id: null }
    methods:  [GET, POST]
