# Resources/config/services.yml
parameters:

    webeweb.bundle.edmbundle.directory: "%kernel.root_dir%/data/edm"

services:

    webeweb.bundle.edmbundle.manager.storage:
        class:     WBW\Bundle\EDMBundle\Manager\StorageManager
        arguments: ["%webeweb.bundle.edmbundle.directory%"]
        public:    true

    webeweb.bundle.edmbundle.twig.extension.edm:
        class:     WBW\Bundle\EDMBundle\Twig\Extension\EDMTwigExtension
        arguments: ["@webeweb.bundle.edmbundle.manager.storage", "@translator"]
        tags:
            - { name: twig.extension }
