# Resources/config/services.yml
parameters:

    webeweb.bundle.edmbundle.directory: "%kernel.root_dir%/data/edm"

services:

    webeweb.bundle.edmbundle.form.type.document.new:
        class:     WBW\Bundle\EDMBundle\Form\Type\Document\NewDocumentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    webeweb.bundle.edmbundle.manager.storage:
        class:     WBW\Bundle\EDMBundle\Manager\StorageManager
        arguments: ["%webeweb.bundle.edmbundle.directory%"]
        public:    true

    webeweb.bundle.edmbundle.twig.extension.edm:
        class:     WBW\Bundle\EDMBundle\Twig\Extension\EDMTwigExtension
        arguments: ["@translator", "@webeweb.bundle.edmbundle.manager.storage"]
        tags:
            - { name: twig.extension }
