# Resources/config/routing/directory.yml
edm_directory_delete:
    path:     /directory/delete/{id}
    defaults: { _controller: "EDMBundle:Directory:delete" }
    methods:  [GET]

edm_directory_edit:
    path:     /directory/edit/{id}
    defaults: { _controller: "EDMBundle:Directory:edit" }
    methods:  [GET, POST]

edm_directory_index:
    path:     /directory/index/{id}
    defaults: { _controller: "EDMBundle:Directory:index", id: null }
    methods:  GET

edm_directory_new:
    path:     /directory/new/{id}
    defaults: { _controller: "EDMBundle:Directory:new", id: null }
    methods:  [GET, POST]
