# Resources/config/validator/validation.yml
WBW\Bundle\EDMBundle\Entity\Document:
    properties:
        name:
            - NotNull: "document.name.notNull.message"
            - Length:
                max: 255
                message: "document.name.length.message"
